language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
  - pip install pytest pytest-cov
  - pip install coveralls
script: py.test --cov
notifications:
  slack: nonatomiclabs:v70RKis1I9cVYwFCjzre8KA1
after_success:
  - coveralls