language: python
python:
  - "2.7"
# command to install dependencies
#before_install:
#  - pip install pytest pytest-cov
# command to run tests
script: py.test
notifications:
  slack: nonatomiclabs:v70RKis1I9cVYwFCjzre8KA1